### ISSUE TITLE
Icon rendering is broken on Kindle Fire HDX

### ISSUE THREAD

**Issue by itkach** [atermenji/IconicDroid#19]
Icons are garbled on 7" Kindle Fire HDX. See attached screenshots. Not all fonts are equally affected: fontawesome and iconic are completely broken while entypo is kind of ok, but not really - there are still rendering artifacts, as if canvas is not properly cleaned up on repaints.
![screenshot_2015-01-08-09-14-24](https://cloud.githubusercontent.com/assets/180849/5664275/3318fe34-971d-11e4-9da2-248a99aa7419.png)
![screenshot_2015-01-08-09-14-54](https://cloud.githubusercontent.com/assets/180849/5664296/62af6836-971d-11e4-97be-3a08bcf673d6.png)
![screenshot_2015-01-08-09-14-42](https://cloud.githubusercontent.com/assets/180849/5664303/75194302-971d-11e4-9915-63b94eba1666.png)
![screenshot_2015-01-08-09-16-00](https://cloud.githubusercontent.com/assets/180849/5664313/8fe2453a-971d-11e4-9c08-e6dbec5e2ac5.png)

**Comment by takke** [comment]
are you tried my fix?

https://github.com/atermenji/IconicDroid/issues/12#issuecomment-43065632

**Comment by atermenji** [comment]
Fixed by @takke
